data_url: 'http://jmcauley.ucsd.edu/cse255/data/beer/Beeradvocate.txt.gz'

data_path: 'data/'

data_name: 'data.csv'

dropped_keys: ['review_text']

train_validation_test_split_ratio: [0.5,0.2]

remove_raw_data: False

learning_rate: .001

regularization_lambda: .02

N_nearest_items: 50

epochs: 3000

latent_dims: 12
