data_url: 'http://jmcauley.ucsd.edu/cse255/data/beer/Beeradvocate.txt.gz'

data_path: 'data/'

data_name: 'data.csv'

dropped_keys: []

remove_raw_data: True

optimizer: 'Adam'

learning_rate: .001

regularization_lambda: .002

N_nearest_items: 50

epochs: 50

batch_size: 128
